project_id = "vehxykvnywjoipghqjos"

[functions.send-contact-email]
verify_jwt = false

[functions.send-reply-email]
verify_jwt = false

[functions.send-booking-email]
verify_jwt = false

[functions.send-landing-submission-email]
verify_jwt = false

[functions.market-news-weather]
verify_jwt = false